#!/bin/sh
set -efu

case $(dpkg --print-architecture) in
    arm64|i386) pys=$(py3versions -d) ;;
    *) pys=$(py3versions -s) ;;
esac

cores=$(nproc)

cp -a cython.py cythonize.py docs tests Demos runtests.py "$AUTOPKGTEST_TMP"
cd "$AUTOPKGTEST_TMP"

for py in $pys; do
	echo "=== $py ==="
	$py runtests.py --shard_count=$cores \
	  --no-refnanny -v -v \
	  --exclude='(parallel|Debugger|annotate_html|numpy_test)' \
	  --work-dir="$AUTOPKGTEST_TMP/test-work-dir"
	rm -rf "$AUTOPKGTEST_TMP/test-work-dir"
done
